services:
  - type: web
    name: contest-app
    runtime: node
    rootDir: backend
    buildCommand: npm install --prefix ../frontend && npm run build --prefix ../frontend && npm install
    startCommand: npm run seed && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: harishcode@admin.com
      - key: ADMIN_PASSWORD
        value: "123456789"
